default: cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/IGameBoard.java
	javac cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/IGameBoard.java

run: cpsc2150/connectX/Connect4Game.class cpsc2150/connectX/GameBoard.class cpsc2150/connectX/GameBoardMem.class cpsc2150/connectX/IGameBoard.class
	java cpsc2150.connectX.Connect4Game cpsc2150.connectX.GameBoard cpsc2150.connectX.GameBoardMem cpsc2150.connectX.IGameBoard

test: cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/TestIGameBoard.java
	javac -cp .:/usr/share/java/junit4.jar cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/TestIGameBoard.java